---
title: सुरक्षा मॉड्यूल
hero_image: images/banner.png
description: सुरक्षा मॉड्यूल
version: 0.1
listed: false
copyedit: true
volunteers: true
last_tested: 2022-01-05
steps:
  - 
    title: बच्चे की सुरक्षा क्या है?
  - 
    title: नियुक्ति प्रक्रिया
    completion:
      - engaged
  - 
    title: नए स्वयंसेवकों को शामिल करना
  - 
    title: बर्ताव का संकेत
  - 
    title: आचार संहिता क्विज
    knowledge_quiz:
      path: क्विज 1
      version: 1
      questions: 9
      passing_score: 9
  - 
    title: दुरुपयोग और अस्वीकरण
  - 
    title: सुरक्षित ऑनलाइन सेशंस कैसे चलाएं
  - 
    title: ऑनलाइन सेशन क्विज
    knowledge_quiz:
      path: क्विज 2
      version: 1
      questions: 3
      passing_score: 3
  - 
    title: क्या करें अगर…
  - 
    title: दुरुपयोग का विवरण किस तरह से रिकॉर्ड करें
  - 
    title: अवलोकन और मूल्यांकन क्विज
    knowledge_quiz:
      path: क्विज 3
      version: 1
      questions: 6
      passing_score: 6
    completion:
      - internal
  - 
    title: यह लगभग यही है!
    completion:
      - external
