---
title: セーフガードモジュール
hero_image: images/banner.png
description: セーフガードモジュール
version: 0.1
listed: false
copyedit: true
volunteers: true
last_tested: 2022-01-05
steps:
  - 
    title: チャイルド・セーフガードとは何ですか?

