---
title: Módulo de salvaguarda
hero_image: images/Safeguarding-Course-Group-1640x824.png
description: Módulo de salvaguarda
version: 0.1
listed: false
copyedit: true
volunteers: true
last_tested: 2022-01-05
steps:
  - 
    title: O que é proteção à criança?

