---
title: ಸುರಕ್ಷೆಯ ಮಾಡ್ಯೂಲ್
hero_image: images/Safeguarding-Course-Group-1640x824.png
description: ಸುರಕ್ಷೆಯ ಮಾಡ್ಯೂಲ್
version: 0.1
listed: false
copyedit: true
volunteers: true
last_tested: 2022-01-05
steps:
  - 
    title: ಮಕ್ಕಳ ರಕ್ಷಣೆ ಎಂದರೇನು?

