---
title: وحدة الحماية
hero_image: images/Code_Club_Safeguarding_Course_Assets_V2_Image 3 - 1280 x 1933.png
description: وحدة الحماية
version: 0.1
listed: false
copyedit: true
volunteers: true
last_tested: 2022-01-05
steps:
  - 
    title: ما هي حماية الطفل؟
  - 
    title: عمليّة التوظيف
    completion:
      - engaged
  - 
    title: تعريف المتطوعين الجدد
  - 
    title: قواعد السلوك
  - 
    title: اختبار قواعد السلوك
    knowledge_quiz:
      path: اختبار1
      version: 1
      questions: 9
      passing_score: 9
  - 
    title: الإساءة والإفصاحات
  - 
    title: كيفية إجراء جلسات آمنة عبر الإنترنت
  - 
    title: اختبار الجلسات عبر الإنترنت
    knowledge_quiz:
      path: اختبار2
      version: 1
      questions: 3
      passing_score: 3
  - 
    title: ماذا تفعل إذا…
  - 
    title: كيفية تسجيل تفاصيل إساءة المعاملة
  - 
    title: اختبار الملاحظات والتقييمات
    knowledge_quiz:
      path: اختبار3
      version: 1
      questions: 6
      passing_score: 6
    completion:
      - internal
  - 
    title: هذا تقريبًا كلّ شيء!
    completion:
      - external
